apiVersion: v1
data:
  browser.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: common.blobstoreFrontend,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      listenAddress: common.httpListenAddress,
    }
kind: ConfigMap
metadata:
  name: browser
  namespace: buildbarn
