apiVersion: v1
data:
  common.libsonnet: |
    {
      blobstore: {
        contentAddressableStorage: {
          sharding: {
            hashInitialization: 11946695773637837490,
            shards: [
              {
                backend: { grpc: { address: 'storage-0.storage:8981' } },
                weight: 1,
              },
              {
                backend: { grpc: { address: 'storage-1.storage:8981' } },
                weight: 1,
              },
            ],
          },
        },
        actionCache: {
          sharding: {
            hashInitialization: 14897363947481274433,
            shards: [
              {
                backend: { grpc: { address: 'storage-0.storage:8981' } },
                weight: 1,
              },
              {
                backend: { grpc: { address: 'storage-1.storage:8981' } },
                weight: 1,
              },
            ],
          },
        },
      },
      # Remember to set your browserUrl to the ingress of the browser deployment
      # browserUrl: 'http://address-of-bb-browser-ingress:80',
      maximumMessageSizeBytes: 16 * 1024 * 1024,
      httpListenAddress: ':80'
    }
kind: ConfigMap
metadata:
  name: common
  namespace: buildbarn
