apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-ubuntu22-04
  namespace: buildbarn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
      instance: ubuntu22-04
  template:
    metadata:
      labels:
        app: scheduler
        instance: ubuntu22-04
    spec:
      containers:
      - args:
        - /config/scheduler.jsonnet
        image: ghcr.io/buildbarn/bb-scheduler:20230905T173453Z-70efb72
        name: scheduler
        ports:
        - containerPort: 8982
          protocol: TCP
        - containerPort: 8983
          protocol: TCP
        - containerPort: 7982
          protocol: TCP
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
      volumes:
      - name: configs
        projected:
          sources:
          - configMap:
              name: scheduler
              items:
              - key: scheduler.jsonnet
                path: scheduler.jsonnet
          - configMap:
              name: common
              items:
              - key: common.libsonnet
                path: common.libsonnet
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
  namespace: buildbarn
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8982
    protocol: TCP
    name: client-grpc
  - port: 8983
    protocol: TCP
    name: worker-grpc
  - port: 7982
    protocol: TCP
    name: http
  selector:
    app: scheduler
    instance: ubuntu22-04
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scheduler
  namespace: buildbarn
spec:
  rules:
  - host: bb-scheduler.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scheduler
            port:
              name: http
