apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-ubuntu22-04
  namespace: buildbarn
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
      instance: ubuntu22-04
  template:
    metadata:
      labels:
        app: worker
        instance: ubuntu22-04
    spec:
      containers:
      - args:
        - /config/worker-ubuntu22-04.jsonnet
        image: buildbarn/bb-worker:20230213T172655Z-e0ae60c
        name: worker
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
        - mountPath: /worker
          mountPropagation: Bidirectional
          name: worker
        - mountPath: /storage-worker-cas
          name: storage-worker-cas
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - command: [/bb/tini, -v, -g, --, /bb/bb_runner, /config/runner-ubuntu22-04.jsonnet]
        image: ghcr.io/catthehacker/ubuntu:act-22.04@sha256:5f9c35c25db1d51a8ddaae5c0ba8d3c163c5e9a4a6cc97acd409ac7eae239448
        name: runner
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
        - mountPath: /worker
          mountPropagation: HostToContainer
          name: worker
        - mountPath: /storage-worker-cas
          name: storage-worker-cas
        - mountPath: /bb
          name: bb-runner
          readOnly: true
      initContainers:
      - name: bb-runner-installer
        image: buildbarn/bb-runner-installer:20230213T172655Z-e0ae60c
        volumeMounts:
        - mountPath: /bb/
          name: bb-runner
      - name: volume-init
        image: busybox:1.31.1-uclibc
        command:
        - sh
        - -c
        - mkdir -pm 0777 /worker/build && mkdir -pm 0700 /worker/cache && mkdir -pm 0777 /storage-worker-cas/persistent_state && mkdir -pm 0777 /worker-fuse && chmod 0777 /worker
        volumeMounts:
        - mountPath: /worker
          mountPropagation: Bidirectional
          name: worker
        - mountPath: /storage-worker-cas
          name: storage-worker-cas
        securityContext:
          privileged: true
      volumes:
      - name: bb-runner
        emptyDir: {}
      - name: configs
        projected:
          sources:
          - configMap:
              name: runner-ubuntu22-04
              items:
              - key: runner-ubuntu22-04.jsonnet
                path: runner-ubuntu22-04.jsonnet
          - configMap:
              name: worker-ubuntu22-04
              items:
              - key: worker-ubuntu22-04.jsonnet
                path: worker-ubuntu22-04.jsonnet
          - configMap:
              name: common
              items:
              - key: common.libsonnet
                path: common.libsonnet
      - name: worker
        hostPath:
          path: /worker-fuse
          type: Directory
      - name: storage-worker-cas
        emptyDir: {}
